services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - '8080:8080'
    networks:
      - otsb_net

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    ports:
      - '3000:3000'
    networks:
      - otsb_net

networks:
  otsb_net:
    external: false
