services:
  mysql:
    image: mysql:8.0
    networks:
      - otsb_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-opentsb}
      MYSQL_USER: ${MYSQL_USER:-otsb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-otsbpass}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-}"]
    networks:
      - otsb_net
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    networks:
      - otsb_net
    ports:
      - '8081:8080'

volumes:
  db_data: {}
  redis_data: {}

networks:
  otsb_net:
    external: false

